### Get all departments (paginated)
GET http://localhost:8080/api/v1/departments

### Get department by ID
GET http://localhost:8080/api/v1/departments/d007

#### Get department by name
#GET http://localhost:8080/api/v1/departments/name/Marketing

### Get department by ID with employees
http://localhost:8080/api/v1/departments/d008/employees/current

### Get department by ID with managers
http://localhost:8080/api/v1/departments/d009/managers

### Create new department
POST http://localhost:8080/api/v1/departments
Content-Type: application/json

{
  "deptNo": "d010",
  "deptName": "Research & Development"
}

### Update department
PUT http://localhost:8080/api/v1/departments/d010
Content-Type: application/json

{
  "deptNo": "d010",
  "deptName": "R&D"
}

### Delete department
DELETE http://localhost:8080/api/v1/departments/d010